export const weatherIconMap = {
  "01d": "wi-day-sunny",        // 맑음 (낮)
  "01n": "wi-night-clear",      // 맑음 (밤)
  "02d": "wi-day-cloudy",       // 구름 조금 (낮)
  "02n": "wi-night-alt-cloudy", // 구름 조금 (밤)
  "03d": "wi-cloud",            // 구름 많음 (낮)
  "03n": "wi-cloud",            // 구름 많음 (밤)
  "04d": "wi-cloudy",           // 흐림 (낮)
  "04n": "wi-cloudy",           // 흐림 (밤)
  "09d": "wi-showers",          // 소나기 (낮)
  "09n": "wi-showers",          // 소나기 (밤)
  "10d": "wi-day-rain",         // 비 (낮)
  "10n": "wi-night-alt-rain",   // 비 (밤)
  "11d": "wi-thunderstorm",     // 천둥번개 (낮)
  "11n": "wi-thunderstorm",     // 천둥번개 (밤)
  "13d": "wi-snow",             // 눈 (낮)
  "13n": "wi-snow",             // 눈 (밤)
  "50d": "wi-fog",              // 안개/박무 (낮)
  "50n": "wi-fog",              // 안개/박무 (밤)
};